# Generated by Django 4.2.11 on 2024-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="id",
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
