# Generated by Django 4.2.11 on 2024-04-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0004_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
